Documentation changes
jonaswinkler/paperless-ng pull request #414
Opened 2021-01-23 12:18 UTC by tido-

Hi, as mentioned in #387 I have made some changes and added some text. At first only for the part of the introduction and Docker installation. Let me know if it fits or if it needs some changes.

2021-01-23 14:13 UTC, C0nsultant requested changes

2021-01-23 14:47 UTC, tido- commented on docs/setup.rst
> +the setup process is fully automated, reproducible and independent,
idempotent  Adj. [**MATH.**]  https://dict.leo.org/englisch-deutsch/idempotent
Thank you for your review and forgive my ignorance, but if this word is only understood by people having studied mathematics?  Is it sensible to put this into a manual?
In Google terms it return's not so many results: Ungefähr 1’850’000 Ergebnisse (0.49 Sekunden) - so I guess it is not widely used. And zero results over here https://corpora.uni-leipzig.de/de/res?corpusId=deu_newscrawl-public_2018&word=Idempotent

How about integrating your explanation?:
The ansible route cobines benefits from both options: the setup process is fully automated, reproducible and it can be applied multiple times without chaning the system state. It comes with the same sensible defaults, and it simultaneously provides the flexibility of a bare metal installation.

_(other than the first run)_ - I guess this is in its nature, so this could be left out?

Last but not least, I don't mind to return your expression - if you insist.

By the way, "It comes with the same sensible defaults" if the docker defaults are changed, are they applied to your script as well?

2021-01-23 16:20 UTC, shamoon commented on docs/setup.rst
> +the setup process is fully automated, reproducible and independent,
FWIW idempotent is used in programming, its also kind of one of _the things_ about ansible. No need to change it imho.

2021-01-23 17:27 UTC, C0nsultant commented on docs/setup.rst
> +the setup process is fully automated, reproducible and independent,
Ok, let's unpack this one...

> this word is only understood by people having studied mathematics

In the ansible world, [idempotency](https://docs.ansible.com/ansible/latest/reference_appendices/glossary.html#Idempotency) is one of the big goals. You provide ansible with the state your target machine should be in, not with the steps on how to get there, a.k.a. *configuration as code*. When the machine is already in that state, nothing needs to be changed.

The term idempotent is relatively well known in the ansible community, and to a lesser degree in (functional) programming. I don't think it's worth elaborating on in the NG documentation.

> How about integrating your explanation?

If you absolutely *must* change it, I would suggest something simple like *minimal*. Alternatively, you could just link to a place in the ansible documentation that explains the concept. Someone familiar with ansible will have no problem reading the NG documentation, others may either not care or be intrigued enough to find out what it means.
Also, out of the three arguments it is IMHO the least important one. Don't put too much time into it.

> if the docker defaults are changed, are they applied to your script as well?

Well the docker setup has no defaults per se. The defaults are hard-coded into the python source code and used when there is no explicit entry in the `paperless.conf` or (correct me if I'm wrong, I'm unfamiliar with the complete docker setup) in the environment variables.
I just replicated the defaults to the [ansible default variables](https://github.com/jonaswinkler/paperless-ng/blob/master/ansible/defaults/main.yml). They will have to be changed when the hard-coded defaults change.

2021-01-24 18:29 UTC, tido- commented on docs/setup.rst
> +the setup process is fully automated, reproducible and independent,
I have heard podcasts about Ansible and Puppet and for recurring tasks or like here I can see the benefit. Also it could attract people like me to get in touch with this software. So, as I initially pointed out it would be nice to not only write this manual in a way experienced understand it, but this is up to you.

I will apply the change in this way:
The ansible route combines benefits of both options:  
the setup process is fully automated, reproducible and idempotent, it includes the same sensible defaults, and it simultaneously provides the flexibility of a bare metal installation.
"" and apply the link https://docs.ansible.com/ansible/latest/reference_appendices/glossary.html#Idempotency ""

2021-01-26 14:50 UTC, jonaswinkler commented on docs/setup.rst
> +the setup process is fully automated, reproducible and independent,
Thanks for making the requested changes.

2021-01-26 14:50 UTC, merged

2021-01-31 13:33 UTC, jonaswinkler commented
@tido- 

Why exactly is step 6 "Now head over to: https://hub.docker.com/r/jonaswinkler/paperless-ng and choose your preferred image and copy the link." required?

The compose files link to "latest", which is good for pretty much all new installations. What kind of link does the user have to select there and why?

2021-01-31 21:11 UTC, tido- commented
Step 6 was not there, so the step: docker pull was missing. Basically you could delete everything but "docker pull, within the directory with the .yml files". 
However, if someday you want to point somebody to a different release, it comes handy to tell this person to follow step 6 and use this link (you might provide then).

2021-02-01 22:02 UTC, tido- commented
I just followed your changes and thought. Did I miss something when I was installing it? It didn't work with `docker-compose up -d` only. 
Now your second commit adds `docker-compose pull`.  In conlusion, it is basically the same as before but with less options ;)

2021-02-01 22:23 UTC, jonaswinkler commented
This is a section about first installs. docker-compose up also pulls if no image is available locally, so this isn't strictly necessary.