Added option to invert thumbnails in dark mode
jonaswinkler/paperless-ng pull request #633
Opened 2021-02-25 13:09 UTC by BolkoSchreiber

see issue #604

2021-02-25 13:49 UTC, shamoon commented
Nice. IMHO I think this should default to true since that’s what it currently is (and is probably more in keeping with dark mode)

2021-02-25 13:53 UTC, shamoon commented
Also could make css more DRY by just using an `inverted` class and rules for `.doc-img.inverted`

(sorry I’m on my phone)

2021-02-25 14:03 UTC, BolkoSchreiber commented
you are right - that default value was a bit selfish :)

About the css: my experience with css is "next to nothing" - but I'll do what i can

2021-02-25 14:07 UTC, shamoon commented
> About the css: my experience with css is "next to nothing"

I can suggest specifics

2021-02-25 14:19 UTC, shamoon requested changes
Please note Im not testing these changes on my machine at the moment in case theres a typo or something but I think you get the idea.

2021-02-25 14:19 UTC, shamoon commented on src-ui/src/app/components/document-list/document-card-large/document-card-large.component.html
> +      <img [src]="getThumbUrl()" class="card-img {{ getIsThumbInverted() ? 'doc-img-inverted' : 'doc-img' }} border-right rounded-left">
`<img [src]="getThumbUrl()" class="card-img doc-img border-right rounded-left"  [class.inverted]="getIsThumbInverted()">`

2021-02-25 14:19 UTC, shamoon commented on src-ui/src/app/components/document-list/document-card-large/document-card-large.component.scss
> +.doc-img, .doc-img-inverted {
`.doc-img {`

2021-02-25 14:19 UTC, shamoon commented on src-ui/src/app/components/document-list/document-card-small/document-card-small.component.scss
> +.doc-img, .doc-img-inverted {
`.doc-img {`

2021-02-25 14:19 UTC, shamoon commented on src-ui/src/app/components/document-list/document-card-small/document-card-small.component.html
> +      <img class="card-img {{ getIsThumbInverted() ? 'doc-img-inverted' : 'doc-img' }} rounded-top" [src]="getThumbUrl()">
`<img class="card-img doc-img rounded-top" [class.inverted]="getIsThumbInverted()" [src]="getThumbUrl()">`

2021-02-25 14:19 UTC, shamoon commented on src-ui/src/theme_dark.scss
> +  .card-selected .doc-img .doc-img-inverted {
`.card-selected .doc-img {`

2021-02-25 14:19 UTC, shamoon commented on src-ui/src/theme_dark.scss
> +  .doc-img-inverted {
`.doc-img.inverted {`

(or if you nest this inside .doc-img you can use &.inverted )

2021-02-25 14:22 UTC, shamoon commented on src-ui/src/theme_dark.scss
>      border-radius: 0;
with other changes this becomes just
`filter: invert(95%) hue-rotate(180deg);`
(other lines become redundant)

2021-02-25 14:36 UTC, BolkoSchreiber commented
Thank you! I think I got it now

2021-02-25 14:42 UTC, shamoon approved these changes

2021-02-25 15:37 UTC, jonaswinkler commented
Seem's you've got it already sorted out! Great.

Maybe it's still a good idea to have the bright thumbnails edited slightly in dark mode (maybe `invert(5%)' or something), just so they're a little easier on the eyes.

2021-02-26 06:45 UTC, BolkoSchreiber commented
ok ... pick one:

0%:
![grafik](https://user-images.githubusercontent.com/52954462/109264491-5d467400-7805-11eb-9f52-99274e3a6f94.png)

5%:
![grafik](https://user-images.githubusercontent.com/52954462/109264860-e9589b80-7805-11eb-8d4a-efc7f91c4101.png)

10% (my favorite):
![grafik](https://user-images.githubusercontent.com/52954462/109264923-02614c80-7806-11eb-9f08-c422fb50e81d.png)

15%:
![grafik](https://user-images.githubusercontent.com/52954462/109265003-2329a200-7806-11eb-9f08-16b94b5b35cb.png)


for the sake of color correctness, I need to add hue-rotate with a fraction of 180°, right? (invert 5% -> 9deg hue-rotate)

2021-02-26 10:58 UTC, jonaswinkler commented
Choose whatever you think looks best!

2021-02-26 11:27 UTC, BolkoSchreiber commented
Alright. 10% it is.

Thank you for your input.

2021-02-26 13:34 UTC, jonaswinkler commented
I've merged this into `dev` manually now, and the PR will show up as merged with the next release.

Next time, please make functional changes on the `dev` branch. `master` always has the code for the latest release.

2021-03-06 12:24 UTC, merged