fix writable check for NFS mounts
jonaswinkler/paperless-ng pull request #715
Opened 2021-03-07 15:14 UTC by rost314

For some reason, os.access(directory, os.W_OK | os.X_OK) does not work correctly on NFS mounts.
After some research, found out that the only secure and portable way to check for write access, is to touch a file.

2021-03-07 19:02 UTC, jonaswinkler requested changes
Thanks for investigating. I have no idea why this does not work properly on NFS volumes; especially since I had a user manually open a python shell in a docker container and run the `os.access()` check on a folder on a NFS share and *it worked* as expected.

See https://github.com/jonaswinkler/paperless-ng/issues/365#issuecomment-761234562 for details.

Can you please change the branch to `dev`?

2021-03-07 19:02 UTC, jonaswinkler commented on src/paperless/checks.py
> +            test_file = os.path.join(directory, 'write_test')
I'd use a filename that's a little more unique and less likely to exist. Maybe `__paperless_write_test__`.

2021-03-07 22:19 UTC, rost314 commented
> 
> 
> Thanks for investigating. I have no idea why this does not work properly on NFS volumes; especially since I had a user manually open a python shell in a docker container and run the `os.access()` check on a folder on a NFS share and _it worked_ as expected.
> 
Easy way to reproduce for me on rasperry with synology mount:
`pi@raspi4:~ $ python3 -c "import os; print(os.access('/mnt/syno_pi/paperless/new_scans', os.W_OK))"
False
pi@raspi4:~ $ ll /mnt/syno_pi/paperless/new_scans
total 140K
drwxrwxrwx 2 pi   pi    4.0K Mar  7 16:33 ./
drwxrwxrwx 5 pi   pi    4.0K Dec 30 13:36 ../`


> See [#365 (comment)](https://github.com/jonaswinkler/paperless-ng/issues/365#issuecomment-761234562) for details.
Thank for pointing me to the conversation, didn't see that before.
> 
> Can you please change the branch to `dev`?
Sure, will do.

2021-03-07 23:01 UTC, rost314 commented on src/paperless/checks.py
> +            test_file = os.path.join(directory, 'write_test')
good point, done.

2021-03-08 11:34 UTC, jonaswinkler approved these changes
Looks good, thank you.

2021-03-08 11:34 UTC, merged