Fix extra scrollbar on log container & reverse log order
jonaswinkler/paperless-ng pull request #778
Opened 2021-03-15 15:40 UTC by shamoon

This PR closes #774 and #775 , it:

- Fixes css that caused an extra scrollbar on the log container
- Reverses the order of log output (newest first)

2021-03-15 15:43 UTC, jonaswinkler commented
> * Reverses the order of log output (newest first)

No. The log may also contain stack traces when critical errors occur, and these are unreadable when reversed. Pretty much all logfiles have the newest entry on the bottom.

2021-03-15 15:45 UTC, shamoon commented
> > * Reverses the order of log output (newest first)
> 
> No. The log may also contain stack traces when critical errors occur, and these are unreadable when reversed. Pretty much all logfiles have the newest entry on the bottom.

Unreadable as in they appear in reverse order and thus hard to understand? Ok I can revert that part of this PR, shoulda waited for your reply...

2021-03-15 15:47 UTC, jonaswinkler commented
> Unreadable as in they appear in reverse order and thus hard to understand?

If anything, make it scroll to the bottom automatically. Github actions does this.

2021-03-15 16:45 UTC, shamoon commented
> > Unreadable as in they appear in reverse order and thus hard to understand?
> 
> Exactly. If anything, make it scroll to the bottom automatically. Github actions does this.

Ok let me see what I can do with that

2021-03-15 16:57 UTC, shamoon commented
Ok check this out LMK

2021-03-16 09:40 UTC, jonaswinkler requested changes

2021-03-16 09:40 UTC, jonaswinkler commented on src-ui/src/app/components/manage/logs/logs.component.ts
> +export class LogsComponent implements AfterViewChecked {
Don't remove OnInit, this has a `ngOnInit` method.

2021-03-16 09:40 UTC, jonaswinkler commented on src-ui/src/app/components/manage/logs/logs.component.ts
> +      this.scrollToBottom()
Is this necessary? Works even without that.

2021-03-16 10:07 UTC, shamoon commented on src-ui/src/app/components/manage/logs/logs.component.ts
> +      this.scrollToBottom()
Doh, yea

2021-03-16 16:29 UTC, merged